Sink Analyser: Fuzzer hit information
ossf/fuzz-introspector pull request #768
Opened 2023-01-17 10:31 UTC by arthurscchan

Add features to show fuzzer hitting information for sink functions. Also provide callpath suggestion for creating fuzzers for specific sink function.

Signed-off-by: Arthur Chan <arthurchan@adalogics.com>

2023-01-17 10:35 UTC, DavidKorczynski requested changes

2023-01-17 10:35 UTC, DavidKorczynski commented on src/fuzz_introspector/analyses/sinks_analyser.py
> +        if the target function is covered by a specific fuzzers
typo: `fuzzer` minus `s`

2023-01-17 11:05 UTC, arthurscchan commented on src/fuzz_introspector/analyses/sinks_analyser.py
> +        if the target function is covered by a specific fuzzers
fixed

2023-01-18 11:00 UTC, DavidKorczynski commented
Could you provide a screenshot?

2023-01-19 10:37 UTC, arthurscchan commented
Currently, if the sink function has no fuzzer reached in runtime, it will dig up all possible callpaths and determine which function is the blocker, that is the function that fail to call down the callpath, together with its information for reference.
![3](https://user-images.githubusercontent.com/33429318/213420380-00a2f9e7-3eb4-41b9-9f8e-8d4aec1d452a.PNG)

2023-01-19 19:47 UTC, DavidKorczynski approved these changes
LGTM

We should add some constraints to avoid showing the HTML as of now since they are not fully ready for displaying on e.g. oss-fuzz. Will do this in a follow-up pr.

ClusterFuzzLite pr is the false positive we've been experiencing lately. No real issue.

2023-01-19 19:48 UTC, merged