Auto-fuzz: Heuristic8 for java
ossf/fuzz-introspector pull request #877
Opened 2023-03-02 10:52 UTC by arthurscchan

Following the change in PR #875, this PR create heuristic 8 to handle non-static method calls which use enum object as part of its arguments.

2023-03-02 11:37 UTC, DavidKorczynski requested changes

2023-03-02 11:37 UTC, DavidKorczynski commented on tools/auto-fuzz/fuzz_driver_generation_jvm.py
> +    #    _generate_heuristic_4(yaml_dict, possible_targets, max_target)
I assume we want to keep these?

2023-03-02 11:37 UTC, DavidKorczynski commented on tools/auto-fuzz/fuzz_driver_generation_jvm.py
> +    #    _generate_heuristic_4(yaml_dict, possible_targets, max_target)
i.e. avoid commenting out?

2023-03-03 03:40 UTC, arthurscchan commented on tools/auto-fuzz/fuzz_driver_generation_jvm.py
> +    #    _generate_heuristic_4(yaml_dict, possible_targets, max_target)
Changed.

2023-03-03 11:07 UTC, DavidKorczynski approved these changes

2023-03-03 11:07 UTC, merged